---
project:
  description: App::FargateStack
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: App::FargateStack
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - README.md
  - share:
    - README.md
    - ChangeLog
  - share/examples:
    - examples/http-test/start-apache
    - examples/http-test/deploy-to-ecr
    - examples/http-test/000-default.conf
    - examples/http-test/apache2.conf
    - examples/http-test/Dockerfile
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/App-FargateStack/issues
  homepage: https://github.com/rlauer6/App-FargateStack
  repository:
    type: git
    url: git@github.com:rlauer6/App-FargateStack.git
    web: https://github.com/rlauer6/App-FargateStack
