#!/usr/bin/env bash
# -*- mode: shell-script; -*-

set -euo pipefail

APACHE_BIN="/usr/sbin/apache2ctl"

START_APACHE=${START_APACHE:-}

if [[ -n "$START_APACHE" ]]; then
    # Start Apache in the foreground
    echo "[$(date +%FT%T)] Launching Apache in foreground..."
    exec "$APACHE_BIN" -D FOREGROUND
fi
